"""Decimal-only contracts for the future Finance Kernel."""

from .contracts import (
    CogsAllocationInput,
    AdvertisingAttribution,
    AdvertisingExpenseInput,
    FinancialFinality,
    FinancialFinalityInput,
    FinancialComponent,
    FinancialComponentInput,
    FinancialComponentStatus,
    FinancialComponentTrace,
    FinancialInput,
    FinancialInputState,
    FinancialResult,
    FinancialStatus,
    MoneyRoundingPolicy,
    RevenueBasis,
    RevenueBasisInput,
    RebillLogisticsClassification,
    RebillLogisticsInput,
    UnresolvedCogsEvent,
    UnresolvedCogsEventInput,
    UnitEconomicsResult,
)
from .kernel import calculate_financial_result
from .finance_detail_adapter import FinanceDetailInputBuildResult, build_financial_input_from_finance_detail
from .marketplace_policy import (
    MARKETPLACE_SIGN_POLICIES,
    POLICY_VERSION,
    MarketplaceEvidence,
    MarketplaceSignPolicy,
    marketplace_component_input,
)

__all__ = [
    "FinancialComponent",
    "CogsAllocationInput",
    "AdvertisingAttribution",
    "AdvertisingExpenseInput",
    "FinancialFinality",
    "FinancialFinalityInput",
    "FinancialComponentInput",
    "FinancialComponentStatus",
    "FinancialComponentTrace",
    "FinancialInput",
    "FinancialInputState",
    "FinancialResult",
    "FinancialStatus",
    "MoneyRoundingPolicy",
    "RevenueBasis",
    "RevenueBasisInput",
    "RebillLogisticsClassification",
    "RebillLogisticsInput",
    "UnresolvedCogsEvent",
    "UnresolvedCogsEventInput",
    "UnitEconomicsResult",
    "calculate_financial_result",
    "FinanceDetailInputBuildResult",
    "build_financial_input_from_finance_detail",
    "MARKETPLACE_SIGN_POLICIES",
    "POLICY_VERSION",
    "MarketplaceEvidence",
    "MarketplaceSignPolicy",
    "marketplace_component_input",
]
