"""Report generator for v5 artifacts."""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from ..domain import MetricsBundle, FactsBundle, CabinetContext


class ReportGenerator:
    """Generates v5 reports in various formats."""

    def __init__(self, cabinet_ctx: CabinetContext):
        self.cabinet_ctx = cabinet_ctx

    def generate_pdf(
        self,
        metrics: MetricsBundle,
        facts: FactsBundle,
        target_date: Optional[date] = None,
        mode: str = "daily",
    ) -> Path:
        """
        Generate a cabinet-scoped PDF report.

        The report is intentionally emitted into v5 artifacts root:
        cabinets/<seller>/v5/artifacts/report.pdf
        """
        report_date = target_date or metrics.period_date
        pdf_path = self.cabinet_ctx.report_pdf_path
        pdf_path.parent.mkdir(parents=True, exist_ok=True)

        c = canvas.Canvas(str(pdf_path), pagesize=A4)
        width, height = A4
        y = height - 40

        c.setFont("Helvetica-Bold", 14)
        c.drawString(40, y, f"WB AI Agent v5 Report ({mode})")
        y -= 22

        c.setFont("Helvetica", 10)
        c.drawString(40, y, f"Cabinet: {metrics.cabinet_id}")
        y -= 14
        c.drawString(40, y, f"Date: {report_date.isoformat()}")
        y -= 14

        portfolio = metrics.portfolio_metrics
        if portfolio is not None:
            c.drawString(40, y, f"Revenue: {portfolio.total_revenue:.2f}")
            y -= 14
            c.drawString(40, y, f"Profit: {portfolio.total_profit:.2f}")
            y -= 14
            c.drawString(40, y, f"ROAS: {portfolio.avg_roas:.4f}")
            y -= 14
            c.drawString(40, y, f"CPC: {portfolio.avg_cpc:.4f}")
            y -= 14
            c.drawString(40, y, f"CTR: {portfolio.avg_ctr:.4f}")
            y -= 18

        c.setFont("Helvetica-Bold", 11)
        c.drawString(40, y, "Top Facts")
        y -= 14
        c.setFont("Helvetica", 9)
        if facts.facts:
            for idx, fact in enumerate(facts.facts[:10], start=1):
                line = f"{idx}. [{fact.type.value}] {fact.title} (sev={fact.severity})"
                c.drawString(40, y, line[:110])
                y -= 12
                if y < 60:
                    c.showPage()
                    c.setFont("Helvetica", 9)
                    y = height - 40
        else:
            c.drawString(40, y, "No facts detected for this run.")
            y -= 12

        c.setFont("Helvetica-Oblique", 8)
        c.drawString(40, 30, "Generated by v5 pipeline only (no v3 fallback)")
        c.save()
        return pdf_path

    def generate_excel(
        self,
        metrics: MetricsBundle,
        facts: FactsBundle,
        target_date: Optional[date] = None,
    ) -> Path:
        """Generate a lightweight placeholder XLSX-compatible artifact."""
        report_date = target_date or metrics.period_date
        reports_dir = self.cabinet_ctx.reports_dir
        reports_dir.mkdir(parents=True, exist_ok=True)
        excel_path = reports_dir / f"report_{report_date.isoformat()}.xlsx"
        excel_path.write_text(
            "Excel export is not implemented yet in v5.\n",
            encoding="utf-8",
        )
        return excel_path
